eduBridge/classroom/urls.py
from django.urls import path
from . import views



urlpatterns =[
    path('home/', views.homeView, name='home'),
    path('courses/', views.course, name='courses'),
    path('course-detail/<str:course_id>/',views.detailCourse, name='course-detail'),
    path('course/<str:course_id>/enroll/', views.enrollment, name='enroll'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('post-assignment/',views.post_AssignmentView, name='create-assignment'),
    path('assignments/',views.Assignment_list, name='assignments'),
    path('submit-assignment/<int:assignment_id>/', views.submit_Assignment, name='submit-assignment'),
    path('submissions/',views.Submission_list, name="submission_list"),
    path('submission/<int:submission_id>/grade/', views.grade, name="grade")
]   

eduBridge/eduBridge/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('eduBridge/auth/', include('Authentication.urls')),
    path('eduBridge/', include('classroom.urls'))
]
if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

from django.conf import settings
from django.urls import include, path

if settings.DEBUG:
    urlpatterns = [
        path('__debug__/', include('debug_toolbar.urls')),
    ] + urlpatterns

eduBridge/classroom/models.py
from django.db import models
from django.contrib.auth.models import User

class Course(models.Model):
	course_name = models.CharField(max_length = 100)
	course_description = models.CharField(max_length = 200)
	course_creator = models.CharField(max_length = 30)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	course_image_cover = models.ImageField(upload_to='pics', null=True)

	def __str__(self):
		return self.course_name

	def is_enrolled_by(self,user):
		if self.enrollments.filter(user=user).exists():
			return True
		else:
			return False

class Assignments(models.Model):
	instructor = models.ForeignKey(User, on_delete=models.CASCADE, related_name='assigments')
	course =models.ForeignKey(Course, on_delete=models.CASCADE,related_name='assigments', null=True)
	title = models.CharField(max_length=200)
	description = models.TextField()
	due_date= models.DateTimeField()
	created_at = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.title


class Submission(models.Model):
	student = models.ForeignKey(User, on_delete=models.CASCADE,related_name='submissions')
	assignment = models.ForeignKey(Assignments, on_delete=models.CASCADE, related_name='submissions')
	content = models.TextField()
	submitted_at = models.DateTimeField(auto_now_add=True)
	graded = models.BooleanField(default=False)
	grade = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
	feedback = models.TextField(null=True)

	def __str__(self):
		return f"{self.student.username}- {self.assignment.title}"


class Enrollment(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='enrollments')
	course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='enrollments')
	enroll_at = models.DateTimeField(auto_now_add=True)


	class meta:
		indexes=[
			models.Index(fields=['user','course'])
		]


	def __str__(self):
		return f'{self.user.username} enrolled in {self.course.course_name}'


class Lessons(models.Model):
	course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='lessons')
	title = models.CharField( max_length=50)
	content = models.TextField()	
	order = models.IntegerField(null=True)

	def __str__(self):
		return f'{self.title}-{self.course.title}'
class Module(models.Model):
	course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='modules')
	title = models.CharField(max_length=50)
	description = models.CharField(max_length=50)
	order = models.IntegerField(null=True)

	class Meta:
		verbose_name = ("Module")
		verbose_name_plural = ("Modules")

	def __str__(self):
		return f'{self.title}'

	

eduBridge/classroom/forms.py
from django import forms
from .models import Assignments,Submission

class AssignmentsForm(forms.ModelForm):
    class Meta:
        model = Assignments
        fields=['title','description','due_date']

class SubmissionForm(forms.ModelForm):
    class Meta:
        model=Submission
        fields=['content']

eduBridge/classroom/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import Course,Assignments,Submission,Enrollment,Lessons,Module
from .forms import AssignmentsForm,SubmissionForm
from django.core.paginator import Paginator
from django.contrib.auth.models import User
from django.contrib import messages
from django.http.response import HttpResponse

def homeView(request):
    course =Course.objects.all()
   
    return render(request, 'classroom/index.html',{'courses':course} )


def course(request):
    course = Course.objects.all()
    context ={
        'courses':course
    }
    return render(request, 'classroom/courses.html', context)

def detailCourse(request,course_id):
    course =get_object_or_404(Course, id=course_id)
    lessons = course.lessons.all().order_by('order')
    modules = course.modules.all().order_by('order')
    user = request.user

    context={
        'course': course,
        'lessons': lessons,
        'modules': modules,
        'user':user
    }
    return render(request, 'classroom/course-detail.html', context)


def profile(request,username):
    user = User.objects.all()
    profile = get_object_or_404(user, username=username)

    return render(request, 'classroom/profile.html',{'profiles':profile})

def post_AssignmentView(request):
    if request.method == 'POST':
        form = AssignmentsForm(request.POST)
        if form.is_valid():
            assignment=form.save(commit=False)
            assignment.instructor=request.user
            assignment.save()
            return redirect('assignments')
    else:
        form = AssignmentsForm()
    return render(request, 'classroom/post-assignment.html', {'form':form})

def Assignment_list(request):
    if request.user.is_staff:
        assignments = Assignments.objects.filter(instructor=request.user)
    else:
        assignments = Assignments.objects.all()

    return render(request, 'classroom/assignments.html', {'assignments':assignments})


def submit_Assignment(request,assignment_id):
    assignment = get_object_or_404(Assignments, id=assignment_id)

    if request.method=='POST':
        form = SubmissionForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.student=request.user
            instance.assignment=assignment
            instance.save()
            return redirect('assignments')
    else:
        form=SubmissionForm()
    return render(request, 'classroom/submit-assignment.html',{'form':form, 'assignment':assignment} )


def  Submission_list(request):
    submission = Submission.objects.all()
    
    return render(request, 'classroom/submission_list.html', {"submissions":submission})


def grade(request,submission_id):
    submission = get_object_or_404(Submission, id=submission_id)
    if request.method == 'POST':
        submission.grade = request.POST.get('grade')
        submission.feedback =  request.POST.get('feedback')
        submission.graded = True
        submission.save()
        return redirect('submission_list')  
    return render(request, 'classroom/grade.html', {'submission': submission})

def enrollment(request,course_id):
    course = get_object_or_404(Course, id=course_id)

    if Enrollment.objects.filter(user = request.user, course=course).exists():
            messages.warning(request, 'You are already enrolled in this course')
    else:
        try:
            Enrollment.objects.create(user=request.user, course=course)
            messages.success(request, 'you have successfully enrolled')
        except exception as e:
            return HttpResponse('An error occured')

    return redirect('course-detail',course_id=course.id)

eduBridge/classroom/templates/classroom/assignments.html
{% extends 'classroom/base.html' %}
{% block content %}
{% for assignment in assignments %}
<div class="assignment">
    <h1>{{assignment.Instructor}}</h1>
    <h2>{{assignment.title}}</h2>
    <h5>{{assignment.description}}</h5>
    <h4>{{assignment.created_at}}</h4>
    <a href="{% url 'submit-assignment' assignment.id %}">Solve</a>
</div>
{% endfor %}

{% endblock content %}

eduBridge/classroom/templates/classroom/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'index.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>EduBridge</title>
</head>

<body>
    <div class="nav navbar">
        <div class="brand">
            <a href="{% url 'home' %}"> <img src="{% static 'logo.jpg' %}" class="rounded-circle" alt="logo"></a>
            <a href="{% url 'home' %}">
                <h4>EduBridge</h4>
            </a>
        </div>
        <div class="nav-links">
            <a href="{% url 'courses' %}">Courses</a>
            <a href="#">Categories</a>
            <a href="#">Level</a>
        </div>
        <div class="form-parent">
            <form>
                <div class="form-grp">
                    <input class="input-search" type="text" name="search" placeholder="search courses...">
                    <button class="input-btn">search</button>
                </div>
            </form>
        </div>

        <div class="auth">
            {% if request.user.is_authenticated %}
            <a href="{% url 'logout' %}">Log out</a>
            <a href="{% url 'profile' request.user.username %}">Profile</a>
            {% else %}
            <a href="{% url 'login' %}">Log in</a>
            {% endif %}
        </div>
    </div>

    <script src="{% static 'bootstrap.min.js' %}"></script>
    {% block content %}
 
    {% endblock content %}
</body>

</html>

eduBridge/classroom/templates/classroom/course-detail.html
{% extends 'classroom/base.html' %}

{% block content %}
<h2>{{ course.course_name}}</h2>
<h4>{{ course.course_description}}</h4>
<p>{{ course.course_creator}}</p>
{% if request.user.enrollment_set.filter(course=course) %}
{% for lesson in lessons  %}
<h4>{{lesson.title}}</h4>
<p>{{lesson.content}}</p>
{% endfor %}
{% else %}
<a href="{% url 'enroll' course.id %}">Enroll</a>
{% endif %}
{% endblock content %}

eduBridge/classroom/templates/classroom/courses.html
{% extends 'classroom/base.html' %}

{% block content %}
<section>
<div class="block ">
  <p class="display-3 mt-4 text-center block">Featured courses</p>
  <div class="course-flex courses">
    {% for course in courses %}
    <div class="card" style="width: 18rem; height: 23em;" h>
      <img src="{{course.course_image_cover.url}}" style="height: 11em;" class="card-img-top" alt="...">
      <div class="card-body text-center">
        <h5 class="card-title">{{course.course_name}}</h5>
        <p class="card-text">{{course.course_creator}}</p>
        <a href="{% url 'course-detail' course.id %}" class="btn btn-primary">view course</a>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
</section>

{% endblock content %}

eduBridge/classroom/templates/classroom/grade.html
{% extends 'classroom/base.html' %}
{% block content %}
<div class="grade-container">
    <div class="grade-headings">
        <p>details</p>
        <h1>Name: <span class="small-text">{{submission.student.username}}</span></h1>
        <h1>Submitted at: <span class="small-text">{{submission.submitted_at}}</span></h1>
        <h1>Assignment: <span class="small-text">{{submission.assignment}}</span></h1>
        <h1>Graded: <span class="small-text">{{submission.graded}}</span></h1>
    </div>

    <form method="post" class="">
        <div class="form-text">
            <p>Question and Answer</p>
            <h1>{{submission.assignment.description}}</h1>
            <p>{{submission.content}}</p>
        </div>
        {% csrf_token %}
        <div class="grade-form">
            <div>
                <label for="grade">Grade:</label>
                <input class="form-control" type="text" name="grade" placeholder="grade">
            </div>
            <div>
                <label for="feedback">Feedback:</label>
                <textarea class="form-control" placeholder="feedback" name="feedback" id="feedback"></textarea>
            </div>
            <button class="btn btn-secondary btn-block mt-4">Submit</button>
        </div>
    </form>
</div>
{% endblock content %}

eduBridge/classroom/templates/classroom/index.html
{% extends 'classroom/base.html' %}
{% load static %}
{% block content %}

<!-- Hero section -->
<div class="container">
  <div class="col ">
    <div class="online">
      <div class="online-text">
        <h2 >One platform,</h2>
        <p class="text-muted"><span class="limitless">limitless learning</span><br> EduBridge is the educational LMS <br> engineered to support students to complete courses.</p>
        <a href="{% url 'register' %}" class="button btn btn-primary btn-xl">Get started</a>
      </div>
      <div class="online-img">
        <img src="{% static 'Student boy.gif' %}">
      </div>
    </div>
  </div>
</div>

<!-- image carousel -->
<div id="carouselExampleSlidesOnly" class="carousel image-carousel block slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{% static 'less.jpg' %}" class="d-block" height="564px" width="864px" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>First slide label</h5>
        <p>Some representative placeholder content for the first slide.</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="{% static 'fess.jpg' %}" class="d-block " height="564px" width="864px" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>First slide label</h5>
        <p>Some representative placeholder content for the first slide.</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="{% static 'student1.jpg' %}" class="d-block " height="564pxs" width="864px" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>First slide label</h5>
        <p>Some representative placeholder content for the first slide.</p>
      </div>
    </div>
  </div>
</div>




<!-- Time section -->
<section>
<div class=" block time">
  <div class="col">
    <div class="time">
      <div class="time-img">
        <img src="{% static 'Waiting Girl.gif' %}">
      </div>
      <div class="time-text">
        <h2 class="text-muted">The Power of Flexible Course <br>Completion.</h2>
        <h1>Learn Anytime,<br> Anywhere</h1>
        <a href="{% url 'courses' %}">Explore courses</a>
      </div>
    </div>
  </div>
</div>
</section>


<!-- Key features -->
<div class="container Key-features block">
  <p class="display-3 text-muted text-center">Key features</p>
  <div class="col d-flex">
    <div class="cards-wrapper1">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title text-center card-heading">Progress Tracking</h5>
          <div class="card-text">
            <ul>
              <li>Real-time analytics</li>
              <li>Certificate of completion</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="cards-wrapper1">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title text-center card-heading">Interactive Tools</h5>
          <div class="card-text">
            <ul>
              <li>Quizzes and assessments</li>
              <li>Discussion forums and peer review</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="cards-wrapper1">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title text-center card-heading">Expert Instructors</h5>
          <div class="card-text">
            <ul>
              <li>1,000+ experienced educators</li>
              <li>Live sessions and Q&A</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- featured-courses -->
<section>
<div class="block flex-block">
  <p class="display-3 text-muted text-center block">Featured courses</p>
  <div class="course-flex">
    {% for course in courses %}
    <div class="card" style="width: 18rem; height: 23em;" h>
      <img src="{{course.course_image_cover.url}}" style="height: 11em;" class="card-img-top" alt="...">
      <div class="card-body text-center">
        <h5 class="card-title">{{course.course_name}}</h5>
        <p class="card-text">{{course.course_creator}}</p>
        <a href="{% url 'course-detail' course.id %}" class="btn btn-primary">view course</a>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
</section>

{% endblock content %}

eduBridge/classroom/templates/classroom/post-assignment.html
{% extends 'classroom/base.html' %}
{% load widget_tweaks %}
{% block content %}
<form method="post">
    {% csrf_token %}
    <div class="post-assignment ">
        <h2>Create an Assigment</h2>
        <div class="form-group">
            <label for="title">title:</label>
            {% render_field form.title class+="form-control" %}
        </div>
        <div class="form-group">
            <label for="description">description:</label>
            {% render_field form.description class+="form-control" %}
        </div>
        <div class="form-group">
            <label for="due_date">due date:</label>
            {% render_field form.due_date class+="form-control" %}
        </div>
        <button class="btn">submit</button>
    </div>
</form>
{% endblock content %}

eduBridge/classroom/templates/classroom/profile.html
{% extends 'classroom/base.html' %}

{% block content %}
{% if request.user.is_staff %}
{% endif %}
<a href="{% url 'create-assignment' %}">create assignment</a><br>
<a href="{% url 'courses' %}">courses</a><br>
<a href="{% url 'assignments' %}">Assignments</a><br>
<a href="{% url 'submission_list' %}">Submissions</a><br>
<p>{{profiles.username}}</p>
{% endblock content %}

eduBridge/classroom/templates/classroom/submission_list.html
{% extends 'classroom/base.html' %}
{% block content %}
{% for submission in submissions %}
{% if submission.assignment.instructor == request.user %}
<div class="submission-list">
    <div>
        <h2>title: {{submission.assignment.title}}</h2>
        <h4>Question: {{ submission.assignment.description}} </h4>
        {% if not submission.graded %}
        <a href="{% url 'grade' submission.id %}">Grade</a>
        {% else %}
        <h4>Grade: {{submission.grade}}</h4> <h4>{{submission.feedback}}</h4>
        <h5>{{ submission.student.username }}</h5>
        <h6>{{ submission.submitted_at }}</h6>
        {% endif %}
    </div>
</div>
<br>
{%endif %}
{% endfor %}
{% endblock content %}

eduBridge/classroom/templates/classroom/submit-assignment.html
{% extends 'classroom/base.html' %}
{% load widget_tweaks %}
{% block content %}

<div class="submit-assignment">
<div>
    <h2>{{assignment.title}}</h2>
    <h5>{{assignment.description}}</h5>
</div>
<form method="post">
    {% csrf_token %}
 
        <div class="form-group">
            <label for="title">Content:</label>
            {% render_field form.content class+="form-control" %}
        </div>
        
        <button class="btn">submit</button>
</form>
</div>
{% endblock content %}